"""add_scheduled_tasks_executions_commands

Revision ID: 906203a21489
Revises: b2c3d4e5f6g7
Create Date: 2026-02-09 16:58:01.403829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906203a21489'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('cron_minute', sa.String(length=20), nullable=True),
    sa.Column('cron_hour', sa.String(length=20), nullable=True),
    sa.Column('cron_dom', sa.String(length=20), nullable=True),
    sa.Column('cron_month', sa.String(length=20), nullable=True),
    sa.Column('cron_dow', sa.String(length=20), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=50), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_tasks_agent_id'), 'scheduled_tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_catalog_key'), 'scheduled_tasks', ['catalog_key'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_id'), 'scheduled_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_next_run_at'), 'scheduled_tasks', ['next_run_at'], unique=False)
    op.create_table('task_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_task_id', sa.Integer(), nullable=True),
    sa.Column('catalog_key', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheduled_task_id'], ['scheduled_tasks.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_executions_catalog_key'), 'task_executions', ['catalog_key'], unique=False)
    op.create_index(op.f('ix_task_executions_id'), 'task_executions', ['id'], unique=False)
    op.create_index(op.f('ix_task_executions_scheduled_task_id'), 'task_executions', ['scheduled_task_id'], unique=False)
    op.create_table('agent_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('catalog_key', sa.String(length=100), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['task_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_commands_agent_id'), 'agent_commands', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_commands_id'), 'agent_commands', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_commands_id'), table_name='agent_commands')
    op.drop_index(op.f('ix_agent_commands_agent_id'), table_name='agent_commands')
    op.drop_table('agent_commands')
    op.drop_index(op.f('ix_task_executions_scheduled_task_id'), table_name='task_executions')
    op.drop_index(op.f('ix_task_executions_id'), table_name='task_executions')
    op.drop_index(op.f('ix_task_executions_catalog_key'), table_name='task_executions')
    op.drop_table('task_executions')
    op.drop_index(op.f('ix_scheduled_tasks_next_run_at'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_catalog_key'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_agent_id'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
