[program:api_cyber]
command=/home/erpnext/api_cyber_env/bin/gunicorn src.main:app -c gunicorn.conf.py
directory=/home/erpnext/.services/api_cyber
user=erpnext
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/api_cyber/supervisor_err.log
stdout_logfile=/var/log/api_cyber/supervisor_out.log
environment=PATH="/home/erpnext/api_cyber_env/bin"

[program:api_cyber_celery]
command=/home/erpnext/api_cyber_env/bin/celery -A src.workers.celery_app worker --loglevel=info
directory=/home/erpnext/.services/api_cyber
user=erpnext
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/api_cyber/celery_err.log
stdout_logfile=/var/log/api_cyber/celery_out.log
environment=PATH="/home/erpnext/api_cyber_env/bin"

[program:api_cyber_celery_beat]
command=/home/erpnext/api_cyber_env/bin/celery -A src.workers.celery_app beat --loglevel=info
directory=/home/erpnext/.services/api_cyber
user=erpnext
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/api_cyber/celery_beat_err.log
stdout_logfile=/var/log/api_cyber/celery_beat_out.log
environment=PATH="/home/erpnext/api_cyber_env/bin"

[program:api_cyber_agent]
command=/home/erpnext/api_cyber_env/bin/python -m agent.src.main
directory=/home/erpnext/.services/api_cyber
user=erpnext
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/api_cyber/agent_err.log
stdout_logfile=/var/log/api_cyber/agent_out.log
environment=PATH="/home/erpnext/api_cyber_env/bin",API_CYBER_URL="https://raquel.pibico.es/cyber",API_CYBER_KEY="%(ENV_API_CYBER_KEY)s",API_CYBER_AGENT_ID="%(ENV_API_CYBER_AGENT_ID)s"
